# Generated by Django 3.0.8 on 2020-08-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
