# Generated by Django 3.1 on 2020-08-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='/profilePics/avatar.svg', upload_to='profilePics'),
        ),
    ]
